services:
  postgres:
    image: postgres:16.0
    container_name: postgres_restaurant_container
    restart: always
    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      TZ: "UTC-4"
    ports:
      - 3030:3030
    command: -p 3030
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/inserts.sql:/docker-entrypoint-initdb.d/2.sql

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: pgadmin_restaurant_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_LISTEN_PORT: 4040
    ports:
      - 4040:4040
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
